### PR TITLE
More conversion changes

### PR DESCRIPTION
**Pull request by KrissN**
Hi,

I was quite busy last week, but this week I have some time to continue. I noticed that you have added some changes yourself.

With this pull request I started to convert the update side of things (I have a nasty reminder dialog that I can't get rid of ;) )

Regards
Chris

### CODE REVIEW

**Comment by 1stsetup** [comment]
Chris,

Good to see. I wanted to mail you about planning/dividing the work so we would not start both on the same parts.
I will continue to change the erXXX.js files. When you need help in converting the updating stuff please let me know.

The update for an item is created in the following way:
1. Convert full old Cal Item to full Exchange Item.
2. Convert full new Cal item to full Exchange Item.
3. Find out the differences between the full old and full new Exchange item on a first level. (xml differences).
4. Send an updateitem request to exchange.

I did not look at the diff yet but how far this you come with the change of the update stuff?

**Comment by KrissN** [comment]
I noticed that this is the way the update goes. I have so far converted the update logic code for calendar appointments (makeUpdateOneItem is converted as long as tasks are not touched - convertCalTaskToExchangeTask conversion is still pending).

One spot I was a bit uncertain is around line 5022 - the original code checks if the XML element from the new element is also present in the old one. The code uses the contains() method, which is not present in the new object. I replaced this with a for each loop, but since you're more familiar with it, you may know a better way to achieve the same functionality.

If you're working on the erXXX.js files, then I'll keep going with the calExchangeCalendar.js file. I plan to convert the convertCalTaskToExchangeTask function and the hunt down any remaining blocks of e4x usage.

**Comment by 1stsetup** [comment]
I will have a look at the contains() function. I have created the xml2jxon from scratch and did not yet implement everything.
tonight I'm going to enhance the namespace support in xml2jxon because the current implementation is giving problems in handling some responses from the exchange server. 
I will have a look at you loop.

**Comment by KrissN** [comment]
I did some more testing on that code and it's heavily buggered. I'll need to sit down and do some debugging.

**Comment by 1stsetup** [comment]
Chris, I did my work on the xml2jxon to make it completely namespace aware. It should solve some bugs. Maybe also one you are hitting. Please update your branche of e4xReplacement.

**Comment by 1stsetup** [comment]
I did not have time to view your latest code yet.It will probably be thursday before get to it.

**Comment by 1stsetup** [comment]
Chris. I fixed a small bug in the xml2jxon object code. This was a bug which popped up when creating a new xml object and adding content which contains special xml characters. These special xml characters did not get converted and this caused the final xml, which gets send to exchange, to be corrupt. This would cause an error from exchange. I do not know if this is the bugs you noticed in your update/change code.

**Comment by KrissN** [comment]
No, these are mine for sure. They're related to the differences between e4x
and xml2jxon objects when comparing the old and new items. The e4x code
can't just be blindly converted - it needs some extra love. I'll try to
find some time to fix them tomorrow.
12 wrz 2012 22:04, "Michel Verbraak" notifications@github.com napisał(a):

**Comment by KrissN** [comment]
I have fixed the comparison code that I initially broke by blindly converting it from e4x to xml2json.

**Comment by 1stsetup** [comment]
Chris did not yet have time to look at it all . Looks very good.
I will have a look on sunday. Thank you.

**Comment by 1stsetup** [comment]
Chris, I'm incorporating your work and debugging it.

**Comment by KrissN** [comment]
This looks like the last bunch of conversion changes in calExchangeCalendar.js.

**Comment by 1stsetup** [comment]
Chris, I manually included you work into the branch e4xReplacement. I had to correct a few parts but it does work in TB15. Please have a look at e4xReplacement branch and let me know.

**Comment by 1stsetup** [comment]
Chris i just saw that you uploaded some new stuff which is not yet in the latest version. I will add it tomorrow. Thank you.

**Pull request closed without merging**
